"""
Django settings for venyuk project.
Generated by 'django-admin startproject' using Django 4.2.25.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-oi2l=nrtoroi9u&@q94j_9i1!getswxwi1kw#740i9lt(6huri'

PRODUCTION = os.getenv('PRODUCTION', 'False').lower() == 'true'

DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "10.0.2.2", "muhammad-fattan-venyuk.pbp.cs.ui.ac.id"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',  # App untuk menangani CORS (Wajib ada)
    'main',
    'venue',
    'ven_shop',
    'match_up',
    'promo',
    'blog',
    'versus',
    'authenticate',
]

# URUTAN MIDDLEWARE YANG BENAR (JANGAN DIUBAH)
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                   # 1. Paling Atas (Wajib)
    'django.middleware.security.SecurityMiddleware',           # 2. Security
    'django.contrib.sessions.middleware.SessionMiddleware',    # 3. Session (Wajib sebelum Auth)
    'django.middleware.common.CommonMiddleware',               # 4. Common
    'django.middleware.csrf.CsrfViewMiddleware',               # 5. CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 6. Auth (Wajib setelah Session)
    'django.contrib.messages.middleware.MessageMiddleware',    # 7. Messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 8. Clickjacking
]

ROOT_URLCONF = 'venyuk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'venyuk.wsgi.application'


# Database
if PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'OPTIONS': {
                'options': f"-c search_path={os.getenv('SCHEMA', 'public')}"
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / 'static'
    ]
else:
    STATIC_ROOT = BASE_DIR / 'static'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File Upload Limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880 

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =================================================================
# KONFIGURASI CORS & SESSION (FIXED UNTUK CHROME FLUTTER WEB)
# =================================================================

# 1. Supaya Chrome mau simpan Cookie Login (Wajib True)
CORS_ALLOW_CREDENTIALS = True

# 2. Supaya tidak diblokir Chrome karena 'Wildcard' (Wajib False jika Credentials=True)
CORS_ALLOW_ALL_ORIGINS = False

# 3. Whitelist Menggunakan REGEX (Pola)
# Ini mengizinkan Flutter Web jalan di PORT BERAPAPUN (localhost:xxx atau 127.0.0.1:xxx)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:[0-9]+$",
    r"^http://127\.0\.0\.1:[0-9]+$",
]

# 4. Daftar Host yang dipercaya untuk CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://10.0.2.2:8000", 
    "https://muhammad-fattan-venyuk.pbp.cs.ui.ac.id",
]

# 5. Setting Cookie agar jalan di HTTP (Localhost)
# Karena kita dev di http://, Secure harus False.
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = False 

# Tambahan: Setting Auth
VERSUS_AUTH_REQUIRED = True