# Generated by Django 5.2.6 on 2025-10-24 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul promo, cth: Promo Spesial Kemerdekaan', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi lengkap promo')),
                ('amount_discount', models.PositiveSmallIntegerField(help_text='Besar diskon dalam persentase (cth: 20 untuk 20%)')),
                ('code', models.CharField(blank=True, editable=False, help_text='Kode promo unik (dibuat otomatis)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('shop', 'Shop'), ('venue', 'Venue')], default='venue', max_length=10)),
                ('max_uses', models.PositiveIntegerField(default=100, help_text='Berapa kali promo ini bisa digunakan')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Tanggal promo mulai aktif')),
                ('end_date', models.DateField(help_text='Tanggal promo berakhir')),
                ('is_active', models.BooleanField(default=True, help_text='Centang jika promo ini aktif dan bisa dilihat publik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
