# Generated by Django 5.2.7 on 2025-10-22 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('badminton', 'Badminton'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('football', 'Football'), ('swimming', 'Swimming'), ('running', 'Running'), ('volleyball', 'Volleyball')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('stock', models.IntegerField()),
                ('reviewer', models.IntegerField()),
                ('brand', models.CharField()),
            ],
        ),
    ]
