# Generated by Django 5.2.7 on 2025-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviewer',
            field=models.IntegerField(default=0),
        ),
    ]
