# Generated by Django 5.2.6 on 2025-12-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
