# Generated by Django 5.2.7 on 2025-10-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven_shop', '0002_alter_product_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
