<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-26 16:37
=======
# Generated by Django 5.2.6 on 2025-10-26 16:37
>>>>>>> 65ade45798b28d9ccb6b226a78339b2636d8eafa

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ven_shop', '0002_alter_product_brand_alter_product_reviewer'),
        ('ven_shop', '0005_purchased_product'),
    ]

    operations = [
    ]
