# Generated by Django 5.2.7 on 2025-10-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ven_shop', '0002_alter_product_brand_alter_product_reviewer'),
        ('ven_shop', '0005_purchased_product'),
    ]

    operations = [
    ]
