# Generated by Django 4.2.25 on 2025-10-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
    ]
