# Generated by Django 4.2.24 on 2025-10-24 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
        ('match_up', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.venue'),
        ),
    ]
