# Generated by Django 5.2.7 on 2025-10-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_added', models.DateField(auto_now=True)),
                ('blog_views', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('e-Sports', 'E-sports'), ('sports', 'Sports'), ('celeberity', 'Celeberity')], max_length=20)),
                ('content_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
