# Generated by Django 5.2.7 on 2025-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('e-sports', 'E-Sports'), ('sports', 'Sports'), ('celeberity', 'Celeberity')], max_length=20),
        ),
    ]
