# Generated by Django 5.2.7 on 2025-10-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_thumbnail_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('e-sports', 'E-Sports'), ('sports', 'Sports'), ('celebrity', 'Celebrity')], max_length=20),
        ),
    ]
