# Generated by Django 5.2.6 on 2025-10-24 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sepak bola', 'Sepak Bola'), ('futsal', 'Futsal'), ('mini soccer', 'Mini Soccer'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('padel', 'Padel'), ('pickle ball', 'Pickle Ball'), ('squash', 'Squash'), ('voli', 'Voli'), ('biliard', 'Biliard'), ('golf', 'Golf'), ('shooting', 'Shooting'), ('tennis meja', 'Tennis Meja')], default='futsal', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('rating', models.FloatField(default=0.0)),
                ('price', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
