# Generated by Django 5.2.7 on 2025-10-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
