# Generated by Django 4.2.24 on 2025-10-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_venue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
