# Generated by Django 5.2.7 on 2025-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_alter_booking_options_venue_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
