# Generated by Django 5.2.5 on 2025-10-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('primary_sport', models.CharField(choices=[('sepak bola', 'Sepak Bola'), ('futsal', 'Futsal'), ('mini soccer', 'Mini Soccer'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('padel', 'Padel'), ('pickle ball', 'Pickle Ball'), ('squash', 'Squash'), ('voli', 'Voli'), ('biliard', 'Biliard'), ('golf', 'Golf'), ('shooting', 'Shooting'), ('tennis meja', 'Tennis Meja')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('sport', models.CharField(choices=[('sepak bola', 'Sepak Bola'), ('futsal', 'Futsal'), ('mini soccer', 'Mini Soccer'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('padel', 'Padel'), ('pickle ball', 'Pickle Ball'), ('squash', 'Squash'), ('voli', 'Voli'), ('biliard', 'Biliard'), ('golf', 'Golf'), ('shooting', 'Shooting'), ('tennis meja', 'Tennis Meja')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('cost_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_challenges', to='versus.community')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_challenges', to='versus.community')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
