# Generated by Django 5.2.5 on 2025-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='match_category',
            field=models.CharField(choices=[('RO16', 'RO16'), ('Cup Final', 'Cup Final'), ('League', 'League'), ('Quarter Final', 'Quarter Final'), ('Semi Final', 'Semi Final')], default='League', max_length=20, verbose_name='Kategori Matchup'),
        ),
    ]
