# Generated by Django 5.2.5 on 2025-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0002_challenge_match_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='players_joined',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='prize_pool',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='venue_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='match_category',
            field=models.CharField(choices=[('ro16', 'RO16'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('cup_final', 'Cup Final'), ('league', 'League')], default='league', max_length=20),
        ),
    ]
