# Generated by Django 5.2.5 on 2025-11-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_booking_options_venue_image_url_venue_user_and_more'),
        ('versus', '0004_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versus_challenges', to='venue.venue'),
        ),
    ]
