# Generated by Django 5.2.5 on 2025-11-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0005_challenge_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='players_joined',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
